theme: jekyll-theme-minimal
title: Caroline Terryn

![Headshot](https://github.com/user-attachments/assets/1ba490a8-0eda-4a68-8f4d-693a82aa6fc4)

description: Northwestern University | B.S. in Mechanical Engineering with a Concentration in Robotics
