theme: jekyll-theme-minimal
title: Caroline Terryn
description: > 
  <img src="https://github.com/user-attachments/assets/1ba490a8-0eda-4a68-8f4d-693a82aa6fc4" 
       alt="Headshot" 
       width="264" 
       height="465">
  <p>
    Northwestern University | B.S. in Mechanical Engineering with a Concentration in Robotics
  </p>
